### ISSUE TITLE
ERROR: Cannot install LAMA and lama==0.1.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by puraminy** [norakassner/LAMA_primed_negated#1]
I get this error when I want to install lama

ERROR: Cannot install LAMA and lama==0.1.2 because these package versions have conflicting dependencies.

Can't it use higher version of torch?

**Comment by norakassner** [comment]
LAMA was developed in 2019 and therefor has some outdated dependency as you noted with torch but also with the transformers library. How do you install LAMA? The authors recommend using environments to circumvent conflicting dependencies.

**Comment by puraminy** [comment]
I don't have the error currently to posit it. However, if you refer to setup.py of LAMA

https://github.com/facebookresearch/LAMA/blob/master/setup.py

The conflict is within the setup packages.
it uses allennlp==0.7.1 which requires a lower version of torch.  I guess I changed it to allennlip==0.8.... and I could install it.

 I still didn't try the project. However, I have some questions. Could you please guide me? 

Can I use your project with multilingual models such as mT5 or mBert? Can I use it in multilingual settings? My other question is that can I extract common sense knowlege via similar method? Do you know related works for this? Multilingual common sense prompting...

**Comment by norakassner** [comment]
This repo has only data for the "negated" and "misprimed" version of LAMA. If you are interested in a multilingual version of data please refer to: https://huggingface.co/datasets/m_lama, https://github.com/norakassner/mlama, https://x-factr.github.io/

**Comment by puraminy** [comment]
thanks for the links
